services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DOCKER_CONTAINER_NAME:-jps-landingpage}
    environment:
      - NODE_ENV=production
      - NUXT_PUBLIC_API_BASE=${API_BASE_URL}
      - NUXT_SITE_URL=${SITE_URL}
      - NUXT_SITE_NAME=${SITE_NAME}
      - NUXT_PUBLIC_SITE_URL=${SITE_URL}
      - NUXT_PUBLIC_SITE_NAME=${SITE_NAME}
      - NUXT_SITE_CONFIG={"url":"${SITE_URL}","name":"${SITE_NAME}"}
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - nginx
    # ports:
    #   - "${APP_PORT:-3000}:3000"
    restart: unless-stopped

networks:
  nginx:
    external: true
    name: nginx
